name: deploy dev

on:
  push:
    branches: [ dev ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run pre --if-present
      - name: upload dist
        env:
          ACCESSKEYID: ${{secrets.ACCESSKEYID}}
          ACCESSKEYSECRET: ${{secrets.ACCESSKEYSECRET}}
          BUILD_DIR: pre
          TARGET_DIR: workflow_dev
        run: node deploy
