name: deploy main

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm install
      - run: npm run build --if-present
      - name: upload dist
        env:
          ACCESSKEYID: ${{secrets.ACCESSKEYID}}
          ACCESSKEYSECRET: ${{secrets.ACCESSKEYSECRET}}
          BUILD_DIR: dist
          TARGET_DIR: workflow
        run: node deploy
